### ISSUE TITLE
Setup a Web Server on AWS Elastic Compute Cloud (EC2)

### ISSUE THREAD

**Issue by jjd90** [jjd90/gitlegion#3]
AWS Elastic Compute Cloud allows us to easily create virtual machines (VM), referred to as instances in AWS, with a base OS image (Amazon Machine Image or AMI). There are different types of instances that define the number of vCPU cores, RAM and storage are provided by default. Instances are currently charged for by the second but when looking up the price you will see it provided for each hour of service the instance uses.You will need to choose the OS that you'd like to use as well as the web server that will be serving up your pages.You also need to think of a secure way to allow all users to access your machine while not sharing credentials (see task below). You should look at the EC2 Userdata service and the cloud-init process on most machines. You should be able to determine a way to provide SSH access without the use of passwords. All users can still use the default account provided on the system.

**Comment by JordanMayhem** [comment]
Creating the EC2 instance involves a few steps. First, the instance must be created through the amazon AWS GUI or via command line using Terraform. 

An issue that I ran into is that you should NOT change the authorized_keys file on the EC2 root user! this is how I lost access to my first EC2...

Instead, create new users with passwords, and within these user's home directory create a /.ssh/authorized_keys. Each of these authorized_keys should have your server's public key listed.

In order to get your public key, you will have to create a key pair. This is done by using the private key file to generate the public key. In Windows the program to do this is called PuttyGen. It is 3rd party. On linux you can run ssh-keygen and that will prompt you to choose a file. The public key output from the ssh-keygen is your public key, and can be copy and pasted into authorized_keys.
