### ISSUE TITLE
Setup your Domain

### ISSUE THREAD

**Issue by jjd90** [jjd90/gitlegion#4]
You domain should use AWS Route53 to serve requests. You will need to setup the provider you purchased your domain from point to your domain on the Route53 servers. You will need to setup the following records in AWS Route53 that will all be served from your webserver.

●    Apex domain
●    www.<yourdomain>

**Comment by oavelar93** [comment]
For this step I purchased a domain from google domains for a year and signed in to copy the name server info from AWS Route 53. On Route 53 I was able to create a Hosted Zone within the Domain Management section and created it under the appropriate domain. I then created Type A And NS Records so that it will route properly.
